project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "MedBionfo_Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - pulse
      - superhero
    css: styles.css
    mainfont: "Inter"
    monofont: "JetBrains Mono"
    fontsize: 1.05rem
    linestretch: 1.7
    toc: true
    toc-title: "Sur cette page"
    toc-depth: 3
    smooth-scroll: true
    anchor-sections: true
    lightbox: true
    link-external-icon: true
    link-external-newwindow: true
